# Generated by Django 4.2.4 on 2023-09-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students_courses", "0001_initial"),
        ("courses", "0002_alter_course_status"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="my_courses",
            field=models.ManyToManyField(
                related_name="students",
                through="students_courses.StudentCourse",
                to="courses.course",
            ),
        ),
    ]
