# Generated by Django 4.2.4 on 2023-09-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("not started", "Default"),
                    ("in progress", "Ip"),
                    ("finished", "Fin"),
                ],
                default="not started",
                max_length=11,
            ),
        ),
    ]
